version: '2' 
services:

  php:
    build:
      context: ./php
      dockerfile: Dockerfile-70
    volumes_from:
      - application
    expose:
      - "9000"
    links:
      - mysql

  application:
    build: ./application
    volumes:
      - ../:/var/www/codeigniter

  data:
    build: ./data
    volumes:
      - /var/lib/mysql
      - /var/lib/mariadb
      - /data
  nginx:
    build: ./nginx
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php

  mysql:
    build: ./mysql
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ci
      MYSQL_USER: ci
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

 redis:
    build: ./redis
    volumes_from:
      - data
    ports:
      - "6378:6379"

  workspace:
    build: ./workspace
    volumes_from:
      - application
    tty: true
